version: "3.8"

networks:
    proxy:
        driver: overlay
        attachable: true
        name: proxy

services:
    traefik:
        image: traefik:v2.4
        networks:
            - proxy
        command:
            - "--log.level=DEBUG"
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=proxy"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
            - "--certificatesresolvers.le.acme.email=shanthi.bunch@gmail.com"
            - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`traefik.shanthi-bunch.ru`)"
            - "traefik.http.routers.api.service=api@internal"
            - "traefik.http.routers.api.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD}"
            - "traefik.http.routers.api.tls.certresolver=le"

    client:
        build: ./client
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.notes.rule=Host(`notes.shanthi-bunch.ru`)"
            - "traefik.http.services.notes.loadbalancer.server.port=3000"
            - "traefik.http.routers.notes.entrypoints=websecure"
            - "traefik.http.routers.notes.tls.certresolver=le"
        networks:
            - proxy

    server:
        build: ./server
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`api.shanthi-bunch.ru`)"
            - "traefik.http.services.api.loadbalancer.server.port=4000"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.tls.certresolver=le"
        networks:
            - proxy

    summarization:
        build: ./summarization
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.summarization.rule=Host(`summarization.shanthi-bunch.ru`)"
            - "traefik.http.services.summarization.loadbalancer.server.port=5000"
            - "traefik.http.routers.summarization.entrypoints=websecure"
            - "traefik.http.routers.summarization.tls.certresolver=le"
        networks:
            - proxy
