name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test_summarization:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - name: Install dependencies
              working-directory: summarization
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest

            - name: Run tests
              working-directory: summarization
              run: |
                  pytest test_app.py

    client_client:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              working-directory: client
              run: npm install

            - name: Run lint
              working-directory: client
              run: npm run lint
